version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/d b
##    healthcheck:
#      test: ["CMD", "mongosh", "--eval", "db.stats()", "-u", "root", "-p", "example", "--authenticationDatabase", "admin"]
#      interval: 10s
#      retries: 5
#      start_period: 30s
#      timeout: 10s
    healthcheck:
     test: ["CMD", "mongo", "--eval", "db.stats()", "-u", "root", "-p", "example", "--authenticationDatabase", "admin"]
     interval: 10s
     retries: 5
     start_period: 30s
     timeout: 10s

  webapp:
    build: .
    container_name: dotnet-mongo-crud
    ports:
      - "3001:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDB__ConnectionString: "mongodb://root:example@mongodb:27017"
      MongoDB__DatabaseName: "ProductDB"
    volumes:
      - ./appsettings.json:/app/appsettings.json

volumes:
  mongo-data:
